// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniformAccountingSystem.Data;

#nullable disable

namespace UniformAccountingSystem.Data.Migrations
{
    [DbContext(typeof(UniformAccountingContext))]
    [Migration("20230504052011_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("WorkPosition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("179287bf-dbea-4e19-ac04-410731a15674"),
                            FirstName = "Александр",
                            LastName = "Черепанов",
                            Patronymic = "Петрович",
                            State = 0,
                            WorkPosition = "роблоксер"
                        },
                        new
                        {
                            Id = new Guid("1ee18c46-4680-430b-b2f8-573f30f1eebb"),
                            FirstName = "Вячеслав",
                            LastName = "Горелов",
                            Patronymic = "Антонович",
                            State = 0,
                            WorkPosition = "разработчик"
                        },
                        new
                        {
                            Id = new Guid("ef4d4fb4-cf1d-4fd3-b148-f4e5455fcccf"),
                            FirstName = "Валерия",
                            LastName = "Косынкова",
                            Patronymic = "Дмитриевна",
                            State = 0,
                            WorkPosition = "грузчик"
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.IssuanceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("IssuanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IssuanceId");

                    b.HasIndex("UniformId");

                    b.ToTable("IssuesItem", t =>
                        {
                            t.HasCheckConstraint("CK_IssuanceItem_Amount", "Amount > 0");
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.ReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("UniformId");

                    b.ToTable("ReceiptItems", t =>
                        {
                            t.HasCheckConstraint("CK_ReceiptItem_Amount", "Amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a61b5e91-1ce1-4fe3-af25-df88d3b9d33b"),
                            Amount = 5,
                            ReceiptId = new Guid("46b2f407-d022-4b7a-8e65-4e1e60c8fd7d"),
                            UniformId = new Guid("ea30c579-a09c-4d5a-9a0c-820c33e9801d")
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.Uniform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("UniformType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UniformTypeRefUniformType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("UniformTypeRefUniformType");

                    b.ToTable("Uniforms", t =>
                        {
                            t.HasCheckConstraint("CK_Uniform_Price", "Price > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea30c579-a09c-4d5a-9a0c-820c33e9801d"),
                            Name = "Штаны обыкновенные",
                            Price = 800.0,
                            UniformType = 0
                        },
                        new
                        {
                            Id = new Guid("3fe835d7-bede-4312-a6a2-de17818a4a43"),
                            Name = "Костюм грузчика",
                            Price = 6000.0,
                            UniformType = 5
                        },
                        new
                        {
                            Id = new Guid("578d6c97-6c40-49cc-8e0f-7f202286110a"),
                            Name = "Футболка роблоксера",
                            Price = 3250.0,
                            UniformType = 0
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformDiscard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UniformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniformId");

                    b.ToTable("Discards", t =>
                        {
                            t.HasCheckConstraint("CK_UniformDiscard_Amount", "Amount > 0");
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformIssuance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desctiption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IssuanceAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IssuanceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 5, 4, 5, 20, 7, 508, DateTimeKind.Utc).AddTicks(8496));

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desctiption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReceiptDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 5, 4, 5, 20, 7, 508, DateTimeKind.Utc).AddTicks(8007));

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46b2f407-d022-4b7a-8e65-4e1e60c8fd7d"),
                            Desctiption = "Первая поставка",
                            ReceiptDate = new DateTime(2023, 5, 4, 5, 20, 7, 509, DateTimeKind.Utc).AddTicks(484),
                            VendorId = new Guid("58be4909-b55c-42fd-a7af-8b01bdcf3a0e")
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformTypeRef", b =>
                {
                    b.Property<int>("UniformType")
                        .HasColumnType("int");

                    b.Property<string>("UniformTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniformType");

                    b.ToTable("UniformTypes");

                    b.HasData(
                        new
                        {
                            UniformType = 0,
                            UniformTypeName = "Other"
                        },
                        new
                        {
                            UniformType = 1,
                            UniformTypeName = "TShirt"
                        },
                        new
                        {
                            UniformType = 2,
                            UniformTypeName = "Patns"
                        },
                        new
                        {
                            UniformType = 3,
                            UniformTypeName = "Shoes"
                        },
                        new
                        {
                            UniformType = 4,
                            UniformTypeName = "Robe"
                        },
                        new
                        {
                            UniformType = 5,
                            UniformTypeName = "Suit"
                        },
                        new
                        {
                            UniformType = 6,
                            UniformTypeName = "Gloves"
                        },
                        new
                        {
                            UniformType = 7,
                            UniformTypeName = "Mask"
                        },
                        new
                        {
                            UniformType = 8,
                            UniformTypeName = "Warm"
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasAlternateKey("Phone");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("626e842b-861d-43cc-b8f6-980602708027"),
                            Description = "Компания много Деловые линии",
                            Email = "dellines@gmail.com",
                            Name = "Деловые линии",
                            Phone = "89996604020"
                        },
                        new
                        {
                            Id = new Guid("58be4909-b55c-42fd-a7af-8b01bdcf3a0e"),
                            Email = "refriver@mail.ru",
                            Name = "ИП Краснореченск",
                            Phone = "89505602033"
                        });
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.IssuanceItem", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.UniformIssuance", "Issuance")
                        .WithMany("IssuanceItems")
                        .HasForeignKey("IssuanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformAccountingSystem.Data.Entities.Uniform", "Uniform")
                        .WithMany()
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issuance");

                    b.Navigation("Uniform");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.ReceiptItem", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.UniformReceipt", "Receipt")
                        .WithMany("ReceiptItems")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformAccountingSystem.Data.Entities.Uniform", "Uniform")
                        .WithMany()
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");

                    b.Navigation("Uniform");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.Uniform", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.UniformTypeRef", "UniformTypeRef")
                        .WithMany()
                        .HasForeignKey("UniformTypeRefUniformType");

                    b.Navigation("UniformTypeRef");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformDiscard", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.Uniform", "Uniform")
                        .WithMany()
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uniform");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformIssuance", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformReceipt", b =>
                {
                    b.HasOne("UniformAccountingSystem.Data.Entities.UniformVendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformIssuance", b =>
                {
                    b.Navigation("IssuanceItems");
                });

            modelBuilder.Entity("UniformAccountingSystem.Data.Entities.UniformReceipt", b =>
                {
                    b.Navigation("ReceiptItems");
                });
#pragma warning restore 612, 618
        }
    }
}
